### PR TITLE
refactor: improve load_icon() fn API

### PR DESCRIPTION
**Pull request by nozwock**
Expands upon #32 
Issue: #31 

Lmao @MrTanoshii, I had also worked on a solution :rofl:

### CODE REVIEW

**Comment by MrTanoshii** [comment]
Oh man, my bad
I'll close this but thanks anyway

Linking #32 , might prove useful in the future

**Comment by nozwock** [comment]
Did you take a look at the changes?

**Comment by MrTanoshii** [comment]
Yup, looks good to me.

I prefer my approach for the image loading but noted that I should have put the hardcoded path in `defines.rs`
I'm also heading off now, I'll make a PR to fix that tomorrow unless you're faster ;P

**Comment by nozwock** [comment]
> but noted that I should have put the hardcoded path in `defines.rs`
> I'm also heading off now, I'll make a PR to fix that tomorrow unless you're faster ;P

??, Isn't that what this PR was? The only other extra stuff I've done is error handling and function name change.

**Pull request closed without merging**
